main/urls.py
from django.urls import path
from main.views import hello_world, kontakty

urlpatterns = [
    path('kontakty/', kontakty),
    path('', hello_world),
]

posts/urls.py
from django.urls import path
from .views import posts_list, posts_details, posts_add

app_name='posts'

urlpatterns = [
    path('', posts_list, name='list'),
    path('<int:post_id>', posts_details, name='details'),
    path('add', posts_add, name='add'),
]

pywww/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls')),
                  path('kontakty/', include('main.urls')),
                  path('posts/', include('posts.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

main/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
import faker as fk
import random

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    def __str__(self):
        return f'Post(title: {self.title})'

    def fill_fake(self):
        f = fk.Faker('PL_pl')
        self.title = f.bs().title()
        self.content = '\n\n'.join(f.paragraphs(random.randint(3, 7)))
        self.published = random.choice([True, False])
        

main/views.py
from django.shortcuts import render


# Create your views here.
def hello_world(request):
    context = {}
    return render(request, 'main/hello.html', context)


def kontakty(request):
    context = {}
    return render(request, 'main/contacts.html', context)

posts/views.py
import django.http

from .models import Post
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse

# Create your views here.
def posts_list(request):
    q = request.GET.get('q')
    context = {}
    posts = Post.objects
    if q:
        posts = posts.filter(title__contains=q)
        context['q'] = q
    if request.GET.get('p'):
        context['p'] = 'on'
        posts = posts.filter(published=True)
    posts = posts.all()

    context['posts'] = posts
    return render(request, 'posts/list.html', context)


def posts_details(request, post_id):
    p = Post.objects.get(id=post_id)
    context = {
        'post': p
    }
    return render(request, 'posts/details.html', context)

def posts_add(request: django.http.HttpRequest):
    if request.method == 'POST':
       print('dodawanie')
       title = request.POST.get('title')
       content = request.POST.get('content')
       published = bool(request.POST.get('published'))
       Post(title=title,
            content=content,
            published=published).save()
       # Post.objects.create()
       return django.http.HttpResponseRedirect(reverse('posts:list'))
    else:
        print('wyświetlanie')

    p = Post.objects.all()
    context = {
        'posts': p
    }
    return render(request, 'posts/add.html', context)

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <!-- Content here -->


    <div class="row">
        <div class="col">
            <img src="{% static 'main/img/logo.png' %}" width="40" height="40"/>
        </div>
        <div class="col-10">
            Tu będzie Nagłówek
        </div>
        <div class="col">

        </div>
    </div>
    {% block content %}
    {% endblock %}
    <div class="row">
        <div class="col">

        </div>
        <div class="col-10">
            Tu będzie Stopka
        </div>
        <div class="col">

        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>
</div>
</body>
</html>

main/templates/main/contacts.html
{% extends "main/base.html" %}
{% block title %}Kontakty{% endblock %}
{% block content %}
Kontakty.
{% endblock %}

main/templates/main/hello.html
{% extends "main/base.html" %}
{% block title %}Strona główna{% endblock %}
{% block content %}
Strona główna.
{% endblock %}

posts/templates/posts/add.html
{% extends "main/base.html" %}
{% block title %}Dodawanie posta{% endblock %}
{% block content %}
<form method="post">
{% csrf_token %}
<div class="row">
    <div class="col"></div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <input type="text" name="title">
                    </li>
                    <li class="list-group-item">
                        <textarea name="content"></textarea>
                    </li>
                    <li class="list-group-item">
                    <input type="checkbox" class="form-check-input" id="addChecked" name="published">
                    <label class="form-check-label" for="addChecked">Opublikowany</label>
                    </li>
                    <li class="list-group-item">
                        <input type="submit" value="Dodaj">
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'posts:list' %}">Powrót do listy postów</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
</form>

{% endblock %}

posts/templates/posts/details.html
{% extends "main/base.html" %}
{% block title %}Szczegóły posta{% endblock %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <h5 class="card-title">{{post.title}}</h5>
                        <h6 class="card-subtitle mb-2 text-body-secondary">
                            Data utworzenia: {{post.created}}</h6>
                        <p class="card-text">{{post.content}}</p>

                    </li>
                    <li class="list-group-item">Opublikowany: {{post.published}}</li>
                    <li class="list-group-item">Data modyfikacji: {{post.modified}}</li>
                    <li class="list-group-item">
                        <a href="{% url 'posts:list' %}">Powrót do listy postów</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>


{% endblock %}

posts/templates/posts/list.html
{% extends "main/base.html" %}
{% block title %}Lista postów{% endblock %}
{% block content %}


<form>
    <div class="row align-items-center">
        <div class="col-1">
        </div>
        <div class="col-1">
                        <a class="btn btn-sm btn-primary" href="{% url 'posts:add'%}">Nowy Post</a>
        </div>
        <div class="col-4">
            <input type="text" class="form-control" id="queryString" name="q" value="{{q}}", placeholder="Szukaj">
        </div>
        <div class="col-2">
            <input type="checkbox" class="form-check-input" id="queryChecked" name="p" {% if p %} checked="True" {% endif %}}>
            <label class="form-check-label" for="queryChecked">Tylko opublikowane</label>
        </div>
        <div class="col-2">
            <button class="btn btn-sm btn-primary" type="submit" value="Szukaj">Szukaj</button>
        </div>
        <div class="col-2">
        </div>
    </div>
</form>


<div class="row">
    <div class="col">

    </div>
    <div class="col-8">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Title</th>
                <th scope="col">Created date</th>
                <th scope="col">Published</th>
            </tr>
            </thead>
            <tbody>
            {% for post in posts %}
            <tr>
                <th scope="row">{{post.id}}</th>
                <td><a href="{% url 'posts:details' post.id %}">{{post.title}}</a></td>
                <td>{{post.created}}</td>
                <td>{{post.published}}</td>
            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
    <div class="col">

    </div>
</div>

{% endblock %}